### ISSUE TITLE
CONNECTING YOUR REMOTE REPO TO A LOCAL REPO?

### ISSUE THREAD

**Issue by CaptRat** [learn-co-curriculum/git-remotes-with-github-readme#13]
This lab doesn't ask us to build a local repo.  In fact, the last lab finishes by suggesting "You can retain the directory as a sandbox for Git experimentation, or simply delete or ignore it."

SO, for those of us trying to understand how to link a remote, ... this explanation is really not very explanatory.
![screen shot 2016-12-22 at 5 59 51 pm](https://cloud.githubusercontent.com/assets/17881768/21444953/86d55fa0-c870-11e6-9764-0367e3dc5ea1.jpg)

**Comment by gj** [comment]
Updated; thanks @CaptRat !
