### ISSUE TITLE
"heavy_plus_sign" Image Link Broken

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/git-remotes-with-github-readme#16]
The image link for the add new repo button appears broken when reading the lesson on learn.co.

<img width="638" alt="screen shot 2018-04-12 at 2 14 47 am" src="https://user-images.githubusercontent.com/5016028/38661674-5256dd3c-3df7-11e8-9d59-e71f34532056.png">

**Comment by drakeltheryuujin** [comment]
Hi @ecssiah,

Thank you for your feedback! I looks like the image has been fixed, but this issue was not yet closed. If it has not been resolved, please feel free to re-open the issue.

💙
