### ISSUE TITLE
for this lesson and previous, get git address from "quick setup" page

### ISSUE THREAD

**Issue by michaelsimon** [learn-co-curriculum/git-remotes-with-github-readme#4]
It looks like you don't see the right hand navigation as described in the lesson until you've made your first commit. On the Code tab of a new repository it displays the "Quick Setup page" with HTTPS or SSH links from where you can copy.

**Comment by AnnJohn** [comment]
thanks @michaelsimon. We'll look into this as soon as we can and update.

**Comment by AnnJohn** [comment]
@mendelB, not a high priority issue but if you have time, can you go through this yourself and see if the instructions need to be changed?
